export const TEST_BOOL_TOGGLE = "TEST_BOOL_TOGGLE";
export const NAV_BAR_ITEM_ON_MOUSE_SET = "NAV_BAR_ITEM_ON_MOUSE_SET";
export const NAV_BAR_ITEM_STYLE_CHANGE = "NAV_BAR_ITEM_STYLE_CHANGE";

export const SLIDESHOW_CAROUSEL_SLIDE_CHANGE = "SLIDESHOW_CAROUSEL_SLIDE_CHANGE";
    export const CAROUSEL_CYCLE_RIGHT = "CYCLE_RIGHT_SLIDE_ACTION";
    export const CAROUSEL_CYCLE_LEFT = "CYCLE_LEFT_SLIDE_ACTION";
    export const CAROUSEL_SELECT_SLIDE_AT_INDEX = "CAROUSEL_SELECT_SLIDE_AT_INDEX";